
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TestServer` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model TestServer
 * 
 */
export type TestServerModel = runtime.Types.Result.DefaultSelection<Prisma.$TestServerPayload>

export type AggregateTestServer = {
  _count: TestServerCountAggregateOutputType | null
  _min: TestServerMinAggregateOutputType | null
  _max: TestServerMaxAggregateOutputType | null
}

export type TestServerMinAggregateOutputType = {
  id: string | null
  name: string | null
  token: string | null
  lastSeen: Date | null
  online: boolean | null
  createdAt: Date | null
  environmentId: string | null
}

export type TestServerMaxAggregateOutputType = {
  id: string | null
  name: string | null
  token: string | null
  lastSeen: Date | null
  online: boolean | null
  createdAt: Date | null
  environmentId: string | null
}

export type TestServerCountAggregateOutputType = {
  id: number
  name: number
  token: number
  lastSeen: number
  online: number
  createdAt: number
  environmentId: number
  _all: number
}


export type TestServerMinAggregateInputType = {
  id?: true
  name?: true
  token?: true
  lastSeen?: true
  online?: true
  createdAt?: true
  environmentId?: true
}

export type TestServerMaxAggregateInputType = {
  id?: true
  name?: true
  token?: true
  lastSeen?: true
  online?: true
  createdAt?: true
  environmentId?: true
}

export type TestServerCountAggregateInputType = {
  id?: true
  name?: true
  token?: true
  lastSeen?: true
  online?: true
  createdAt?: true
  environmentId?: true
  _all?: true
}

export type TestServerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TestServer to aggregate.
   */
  where?: Prisma.TestServerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TestServers to fetch.
   */
  orderBy?: Prisma.TestServerOrderByWithRelationInput | Prisma.TestServerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TestServerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TestServers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TestServers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TestServers
  **/
  _count?: true | TestServerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TestServerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TestServerMaxAggregateInputType
}

export type GetTestServerAggregateType<T extends TestServerAggregateArgs> = {
      [P in keyof T & keyof AggregateTestServer]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTestServer[P]>
    : Prisma.GetScalarType<T[P], AggregateTestServer[P]>
}




export type TestServerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TestServerWhereInput
  orderBy?: Prisma.TestServerOrderByWithAggregationInput | Prisma.TestServerOrderByWithAggregationInput[]
  by: Prisma.TestServerScalarFieldEnum[] | Prisma.TestServerScalarFieldEnum
  having?: Prisma.TestServerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TestServerCountAggregateInputType | true
  _min?: TestServerMinAggregateInputType
  _max?: TestServerMaxAggregateInputType
}

export type TestServerGroupByOutputType = {
  id: string
  name: string
  token: string
  lastSeen: Date | null
  online: boolean
  createdAt: Date
  environmentId: string | null
  _count: TestServerCountAggregateOutputType | null
  _min: TestServerMinAggregateOutputType | null
  _max: TestServerMaxAggregateOutputType | null
}

type GetTestServerGroupByPayload<T extends TestServerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TestServerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TestServerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TestServerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TestServerGroupByOutputType[P]>
      }
    >
  >



export type TestServerWhereInput = {
  AND?: Prisma.TestServerWhereInput | Prisma.TestServerWhereInput[]
  OR?: Prisma.TestServerWhereInput[]
  NOT?: Prisma.TestServerWhereInput | Prisma.TestServerWhereInput[]
  id?: Prisma.StringFilter<"TestServer"> | string
  name?: Prisma.StringFilter<"TestServer"> | string
  token?: Prisma.StringFilter<"TestServer"> | string
  lastSeen?: Prisma.DateTimeNullableFilter<"TestServer"> | Date | string | null
  online?: Prisma.BoolFilter<"TestServer"> | boolean
  createdAt?: Prisma.DateTimeFilter<"TestServer"> | Date | string
  environmentId?: Prisma.StringNullableFilter<"TestServer"> | string | null
  environment?: Prisma.XOR<Prisma.EnvironmentNullableScalarRelationFilter, Prisma.EnvironmentWhereInput> | null
}

export type TestServerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  token?: Prisma.SortOrder
  lastSeen?: Prisma.SortOrderInput | Prisma.SortOrder
  online?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  environmentId?: Prisma.SortOrderInput | Prisma.SortOrder
  environment?: Prisma.EnvironmentOrderByWithRelationInput
}

export type TestServerWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  AND?: Prisma.TestServerWhereInput | Prisma.TestServerWhereInput[]
  OR?: Prisma.TestServerWhereInput[]
  NOT?: Prisma.TestServerWhereInput | Prisma.TestServerWhereInput[]
  token?: Prisma.StringFilter<"TestServer"> | string
  lastSeen?: Prisma.DateTimeNullableFilter<"TestServer"> | Date | string | null
  online?: Prisma.BoolFilter<"TestServer"> | boolean
  createdAt?: Prisma.DateTimeFilter<"TestServer"> | Date | string
  environmentId?: Prisma.StringNullableFilter<"TestServer"> | string | null
  environment?: Prisma.XOR<Prisma.EnvironmentNullableScalarRelationFilter, Prisma.EnvironmentWhereInput> | null
}, "id" | "name">

export type TestServerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  token?: Prisma.SortOrder
  lastSeen?: Prisma.SortOrderInput | Prisma.SortOrder
  online?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  environmentId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.TestServerCountOrderByAggregateInput
  _max?: Prisma.TestServerMaxOrderByAggregateInput
  _min?: Prisma.TestServerMinOrderByAggregateInput
}

export type TestServerScalarWhereWithAggregatesInput = {
  AND?: Prisma.TestServerScalarWhereWithAggregatesInput | Prisma.TestServerScalarWhereWithAggregatesInput[]
  OR?: Prisma.TestServerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TestServerScalarWhereWithAggregatesInput | Prisma.TestServerScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TestServer"> | string
  name?: Prisma.StringWithAggregatesFilter<"TestServer"> | string
  token?: Prisma.StringWithAggregatesFilter<"TestServer"> | string
  lastSeen?: Prisma.DateTimeNullableWithAggregatesFilter<"TestServer"> | Date | string | null
  online?: Prisma.BoolWithAggregatesFilter<"TestServer"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TestServer"> | Date | string
  environmentId?: Prisma.StringNullableWithAggregatesFilter<"TestServer"> | string | null
}

export type TestServerCreateInput = {
  id?: string
  name: string
  token: string
  lastSeen?: Date | string | null
  online?: boolean
  createdAt?: Date | string
  environment?: Prisma.EnvironmentCreateNestedOneWithoutServersInput
}

export type TestServerUncheckedCreateInput = {
  id?: string
  name: string
  token: string
  lastSeen?: Date | string | null
  online?: boolean
  createdAt?: Date | string
  environmentId?: string | null
}

export type TestServerUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  lastSeen?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  online?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  environment?: Prisma.EnvironmentUpdateOneWithoutServersNestedInput
}

export type TestServerUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  lastSeen?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  online?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  environmentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TestServerCreateManyInput = {
  id?: string
  name: string
  token: string
  lastSeen?: Date | string | null
  online?: boolean
  createdAt?: Date | string
  environmentId?: string | null
}

export type TestServerUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  lastSeen?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  online?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TestServerUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  lastSeen?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  online?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  environmentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TestServerListRelationFilter = {
  every?: Prisma.TestServerWhereInput
  some?: Prisma.TestServerWhereInput
  none?: Prisma.TestServerWhereInput
}

export type TestServerOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TestServerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  token?: Prisma.SortOrder
  lastSeen?: Prisma.SortOrder
  online?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  environmentId?: Prisma.SortOrder
}

export type TestServerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  token?: Prisma.SortOrder
  lastSeen?: Prisma.SortOrder
  online?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  environmentId?: Prisma.SortOrder
}

export type TestServerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  token?: Prisma.SortOrder
  lastSeen?: Prisma.SortOrder
  online?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  environmentId?: Prisma.SortOrder
}

export type TestServerCreateNestedManyWithoutEnvironmentInput = {
  create?: Prisma.XOR<Prisma.TestServerCreateWithoutEnvironmentInput, Prisma.TestServerUncheckedCreateWithoutEnvironmentInput> | Prisma.TestServerCreateWithoutEnvironmentInput[] | Prisma.TestServerUncheckedCreateWithoutEnvironmentInput[]
  connectOrCreate?: Prisma.TestServerCreateOrConnectWithoutEnvironmentInput | Prisma.TestServerCreateOrConnectWithoutEnvironmentInput[]
  createMany?: Prisma.TestServerCreateManyEnvironmentInputEnvelope
  connect?: Prisma.TestServerWhereUniqueInput | Prisma.TestServerWhereUniqueInput[]
}

export type TestServerUncheckedCreateNestedManyWithoutEnvironmentInput = {
  create?: Prisma.XOR<Prisma.TestServerCreateWithoutEnvironmentInput, Prisma.TestServerUncheckedCreateWithoutEnvironmentInput> | Prisma.TestServerCreateWithoutEnvironmentInput[] | Prisma.TestServerUncheckedCreateWithoutEnvironmentInput[]
  connectOrCreate?: Prisma.TestServerCreateOrConnectWithoutEnvironmentInput | Prisma.TestServerCreateOrConnectWithoutEnvironmentInput[]
  createMany?: Prisma.TestServerCreateManyEnvironmentInputEnvelope
  connect?: Prisma.TestServerWhereUniqueInput | Prisma.TestServerWhereUniqueInput[]
}

export type TestServerUpdateManyWithoutEnvironmentNestedInput = {
  create?: Prisma.XOR<Prisma.TestServerCreateWithoutEnvironmentInput, Prisma.TestServerUncheckedCreateWithoutEnvironmentInput> | Prisma.TestServerCreateWithoutEnvironmentInput[] | Prisma.TestServerUncheckedCreateWithoutEnvironmentInput[]
  connectOrCreate?: Prisma.TestServerCreateOrConnectWithoutEnvironmentInput | Prisma.TestServerCreateOrConnectWithoutEnvironmentInput[]
  upsert?: Prisma.TestServerUpsertWithWhereUniqueWithoutEnvironmentInput | Prisma.TestServerUpsertWithWhereUniqueWithoutEnvironmentInput[]
  createMany?: Prisma.TestServerCreateManyEnvironmentInputEnvelope
  set?: Prisma.TestServerWhereUniqueInput | Prisma.TestServerWhereUniqueInput[]
  disconnect?: Prisma.TestServerWhereUniqueInput | Prisma.TestServerWhereUniqueInput[]
  delete?: Prisma.TestServerWhereUniqueInput | Prisma.TestServerWhereUniqueInput[]
  connect?: Prisma.TestServerWhereUniqueInput | Prisma.TestServerWhereUniqueInput[]
  update?: Prisma.TestServerUpdateWithWhereUniqueWithoutEnvironmentInput | Prisma.TestServerUpdateWithWhereUniqueWithoutEnvironmentInput[]
  updateMany?: Prisma.TestServerUpdateManyWithWhereWithoutEnvironmentInput | Prisma.TestServerUpdateManyWithWhereWithoutEnvironmentInput[]
  deleteMany?: Prisma.TestServerScalarWhereInput | Prisma.TestServerScalarWhereInput[]
}

export type TestServerUncheckedUpdateManyWithoutEnvironmentNestedInput = {
  create?: Prisma.XOR<Prisma.TestServerCreateWithoutEnvironmentInput, Prisma.TestServerUncheckedCreateWithoutEnvironmentInput> | Prisma.TestServerCreateWithoutEnvironmentInput[] | Prisma.TestServerUncheckedCreateWithoutEnvironmentInput[]
  connectOrCreate?: Prisma.TestServerCreateOrConnectWithoutEnvironmentInput | Prisma.TestServerCreateOrConnectWithoutEnvironmentInput[]
  upsert?: Prisma.TestServerUpsertWithWhereUniqueWithoutEnvironmentInput | Prisma.TestServerUpsertWithWhereUniqueWithoutEnvironmentInput[]
  createMany?: Prisma.TestServerCreateManyEnvironmentInputEnvelope
  set?: Prisma.TestServerWhereUniqueInput | Prisma.TestServerWhereUniqueInput[]
  disconnect?: Prisma.TestServerWhereUniqueInput | Prisma.TestServerWhereUniqueInput[]
  delete?: Prisma.TestServerWhereUniqueInput | Prisma.TestServerWhereUniqueInput[]
  connect?: Prisma.TestServerWhereUniqueInput | Prisma.TestServerWhereUniqueInput[]
  update?: Prisma.TestServerUpdateWithWhereUniqueWithoutEnvironmentInput | Prisma.TestServerUpdateWithWhereUniqueWithoutEnvironmentInput[]
  updateMany?: Prisma.TestServerUpdateManyWithWhereWithoutEnvironmentInput | Prisma.TestServerUpdateManyWithWhereWithoutEnvironmentInput[]
  deleteMany?: Prisma.TestServerScalarWhereInput | Prisma.TestServerScalarWhereInput[]
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type TestServerCreateWithoutEnvironmentInput = {
  id?: string
  name: string
  token: string
  lastSeen?: Date | string | null
  online?: boolean
  createdAt?: Date | string
}

export type TestServerUncheckedCreateWithoutEnvironmentInput = {
  id?: string
  name: string
  token: string
  lastSeen?: Date | string | null
  online?: boolean
  createdAt?: Date | string
}

export type TestServerCreateOrConnectWithoutEnvironmentInput = {
  where: Prisma.TestServerWhereUniqueInput
  create: Prisma.XOR<Prisma.TestServerCreateWithoutEnvironmentInput, Prisma.TestServerUncheckedCreateWithoutEnvironmentInput>
}

export type TestServerCreateManyEnvironmentInputEnvelope = {
  data: Prisma.TestServerCreateManyEnvironmentInput | Prisma.TestServerCreateManyEnvironmentInput[]
  skipDuplicates?: boolean
}

export type TestServerUpsertWithWhereUniqueWithoutEnvironmentInput = {
  where: Prisma.TestServerWhereUniqueInput
  update: Prisma.XOR<Prisma.TestServerUpdateWithoutEnvironmentInput, Prisma.TestServerUncheckedUpdateWithoutEnvironmentInput>
  create: Prisma.XOR<Prisma.TestServerCreateWithoutEnvironmentInput, Prisma.TestServerUncheckedCreateWithoutEnvironmentInput>
}

export type TestServerUpdateWithWhereUniqueWithoutEnvironmentInput = {
  where: Prisma.TestServerWhereUniqueInput
  data: Prisma.XOR<Prisma.TestServerUpdateWithoutEnvironmentInput, Prisma.TestServerUncheckedUpdateWithoutEnvironmentInput>
}

export type TestServerUpdateManyWithWhereWithoutEnvironmentInput = {
  where: Prisma.TestServerScalarWhereInput
  data: Prisma.XOR<Prisma.TestServerUpdateManyMutationInput, Prisma.TestServerUncheckedUpdateManyWithoutEnvironmentInput>
}

export type TestServerScalarWhereInput = {
  AND?: Prisma.TestServerScalarWhereInput | Prisma.TestServerScalarWhereInput[]
  OR?: Prisma.TestServerScalarWhereInput[]
  NOT?: Prisma.TestServerScalarWhereInput | Prisma.TestServerScalarWhereInput[]
  id?: Prisma.StringFilter<"TestServer"> | string
  name?: Prisma.StringFilter<"TestServer"> | string
  token?: Prisma.StringFilter<"TestServer"> | string
  lastSeen?: Prisma.DateTimeNullableFilter<"TestServer"> | Date | string | null
  online?: Prisma.BoolFilter<"TestServer"> | boolean
  createdAt?: Prisma.DateTimeFilter<"TestServer"> | Date | string
  environmentId?: Prisma.StringNullableFilter<"TestServer"> | string | null
}

export type TestServerCreateManyEnvironmentInput = {
  id?: string
  name: string
  token: string
  lastSeen?: Date | string | null
  online?: boolean
  createdAt?: Date | string
}

export type TestServerUpdateWithoutEnvironmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  lastSeen?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  online?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TestServerUncheckedUpdateWithoutEnvironmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  lastSeen?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  online?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TestServerUncheckedUpdateManyWithoutEnvironmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  lastSeen?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  online?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TestServerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  token?: boolean
  lastSeen?: boolean
  online?: boolean
  createdAt?: boolean
  environmentId?: boolean
  environment?: boolean | Prisma.TestServer$environmentArgs<ExtArgs>
}, ExtArgs["result"]["testServer"]>

export type TestServerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  token?: boolean
  lastSeen?: boolean
  online?: boolean
  createdAt?: boolean
  environmentId?: boolean
  environment?: boolean | Prisma.TestServer$environmentArgs<ExtArgs>
}, ExtArgs["result"]["testServer"]>

export type TestServerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  token?: boolean
  lastSeen?: boolean
  online?: boolean
  createdAt?: boolean
  environmentId?: boolean
  environment?: boolean | Prisma.TestServer$environmentArgs<ExtArgs>
}, ExtArgs["result"]["testServer"]>

export type TestServerSelectScalar = {
  id?: boolean
  name?: boolean
  token?: boolean
  lastSeen?: boolean
  online?: boolean
  createdAt?: boolean
  environmentId?: boolean
}

export type TestServerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "token" | "lastSeen" | "online" | "createdAt" | "environmentId", ExtArgs["result"]["testServer"]>
export type TestServerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  environment?: boolean | Prisma.TestServer$environmentArgs<ExtArgs>
}
export type TestServerIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  environment?: boolean | Prisma.TestServer$environmentArgs<ExtArgs>
}
export type TestServerIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  environment?: boolean | Prisma.TestServer$environmentArgs<ExtArgs>
}

export type $TestServerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TestServer"
  objects: {
    environment: Prisma.$EnvironmentPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    token: string
    lastSeen: Date | null
    online: boolean
    createdAt: Date
    environmentId: string | null
  }, ExtArgs["result"]["testServer"]>
  composites: {}
}

export type TestServerGetPayload<S extends boolean | null | undefined | TestServerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TestServerPayload, S>

export type TestServerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TestServerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TestServerCountAggregateInputType | true
  }

export interface TestServerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TestServer'], meta: { name: 'TestServer' } }
  /**
   * Find zero or one TestServer that matches the filter.
   * @param {TestServerFindUniqueArgs} args - Arguments to find a TestServer
   * @example
   * // Get one TestServer
   * const testServer = await prisma.testServer.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TestServerFindUniqueArgs>(args: Prisma.SelectSubset<T, TestServerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TestServerClient<runtime.Types.Result.GetResult<Prisma.$TestServerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TestServer that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TestServerFindUniqueOrThrowArgs} args - Arguments to find a TestServer
   * @example
   * // Get one TestServer
   * const testServer = await prisma.testServer.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TestServerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TestServerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TestServerClient<runtime.Types.Result.GetResult<Prisma.$TestServerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TestServer that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TestServerFindFirstArgs} args - Arguments to find a TestServer
   * @example
   * // Get one TestServer
   * const testServer = await prisma.testServer.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TestServerFindFirstArgs>(args?: Prisma.SelectSubset<T, TestServerFindFirstArgs<ExtArgs>>): Prisma.Prisma__TestServerClient<runtime.Types.Result.GetResult<Prisma.$TestServerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TestServer that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TestServerFindFirstOrThrowArgs} args - Arguments to find a TestServer
   * @example
   * // Get one TestServer
   * const testServer = await prisma.testServer.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TestServerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TestServerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TestServerClient<runtime.Types.Result.GetResult<Prisma.$TestServerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TestServers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TestServerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TestServers
   * const testServers = await prisma.testServer.findMany()
   * 
   * // Get first 10 TestServers
   * const testServers = await prisma.testServer.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const testServerWithIdOnly = await prisma.testServer.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TestServerFindManyArgs>(args?: Prisma.SelectSubset<T, TestServerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TestServerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TestServer.
   * @param {TestServerCreateArgs} args - Arguments to create a TestServer.
   * @example
   * // Create one TestServer
   * const TestServer = await prisma.testServer.create({
   *   data: {
   *     // ... data to create a TestServer
   *   }
   * })
   * 
   */
  create<T extends TestServerCreateArgs>(args: Prisma.SelectSubset<T, TestServerCreateArgs<ExtArgs>>): Prisma.Prisma__TestServerClient<runtime.Types.Result.GetResult<Prisma.$TestServerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TestServers.
   * @param {TestServerCreateManyArgs} args - Arguments to create many TestServers.
   * @example
   * // Create many TestServers
   * const testServer = await prisma.testServer.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TestServerCreateManyArgs>(args?: Prisma.SelectSubset<T, TestServerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TestServers and returns the data saved in the database.
   * @param {TestServerCreateManyAndReturnArgs} args - Arguments to create many TestServers.
   * @example
   * // Create many TestServers
   * const testServer = await prisma.testServer.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TestServers and only return the `id`
   * const testServerWithIdOnly = await prisma.testServer.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TestServerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TestServerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TestServerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TestServer.
   * @param {TestServerDeleteArgs} args - Arguments to delete one TestServer.
   * @example
   * // Delete one TestServer
   * const TestServer = await prisma.testServer.delete({
   *   where: {
   *     // ... filter to delete one TestServer
   *   }
   * })
   * 
   */
  delete<T extends TestServerDeleteArgs>(args: Prisma.SelectSubset<T, TestServerDeleteArgs<ExtArgs>>): Prisma.Prisma__TestServerClient<runtime.Types.Result.GetResult<Prisma.$TestServerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TestServer.
   * @param {TestServerUpdateArgs} args - Arguments to update one TestServer.
   * @example
   * // Update one TestServer
   * const testServer = await prisma.testServer.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TestServerUpdateArgs>(args: Prisma.SelectSubset<T, TestServerUpdateArgs<ExtArgs>>): Prisma.Prisma__TestServerClient<runtime.Types.Result.GetResult<Prisma.$TestServerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TestServers.
   * @param {TestServerDeleteManyArgs} args - Arguments to filter TestServers to delete.
   * @example
   * // Delete a few TestServers
   * const { count } = await prisma.testServer.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TestServerDeleteManyArgs>(args?: Prisma.SelectSubset<T, TestServerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TestServers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TestServerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TestServers
   * const testServer = await prisma.testServer.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TestServerUpdateManyArgs>(args: Prisma.SelectSubset<T, TestServerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TestServers and returns the data updated in the database.
   * @param {TestServerUpdateManyAndReturnArgs} args - Arguments to update many TestServers.
   * @example
   * // Update many TestServers
   * const testServer = await prisma.testServer.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TestServers and only return the `id`
   * const testServerWithIdOnly = await prisma.testServer.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TestServerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TestServerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TestServerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TestServer.
   * @param {TestServerUpsertArgs} args - Arguments to update or create a TestServer.
   * @example
   * // Update or create a TestServer
   * const testServer = await prisma.testServer.upsert({
   *   create: {
   *     // ... data to create a TestServer
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TestServer we want to update
   *   }
   * })
   */
  upsert<T extends TestServerUpsertArgs>(args: Prisma.SelectSubset<T, TestServerUpsertArgs<ExtArgs>>): Prisma.Prisma__TestServerClient<runtime.Types.Result.GetResult<Prisma.$TestServerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TestServers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TestServerCountArgs} args - Arguments to filter TestServers to count.
   * @example
   * // Count the number of TestServers
   * const count = await prisma.testServer.count({
   *   where: {
   *     // ... the filter for the TestServers we want to count
   *   }
   * })
  **/
  count<T extends TestServerCountArgs>(
    args?: Prisma.Subset<T, TestServerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TestServerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TestServer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TestServerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TestServerAggregateArgs>(args: Prisma.Subset<T, TestServerAggregateArgs>): Prisma.PrismaPromise<GetTestServerAggregateType<T>>

  /**
   * Group by TestServer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TestServerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TestServerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TestServerGroupByArgs['orderBy'] }
      : { orderBy?: TestServerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TestServerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTestServerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TestServer model
 */
readonly fields: TestServerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TestServer.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TestServerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  environment<T extends Prisma.TestServer$environmentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TestServer$environmentArgs<ExtArgs>>): Prisma.Prisma__EnvironmentClient<runtime.Types.Result.GetResult<Prisma.$EnvironmentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TestServer model
 */
export interface TestServerFieldRefs {
  readonly id: Prisma.FieldRef<"TestServer", 'String'>
  readonly name: Prisma.FieldRef<"TestServer", 'String'>
  readonly token: Prisma.FieldRef<"TestServer", 'String'>
  readonly lastSeen: Prisma.FieldRef<"TestServer", 'DateTime'>
  readonly online: Prisma.FieldRef<"TestServer", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"TestServer", 'DateTime'>
  readonly environmentId: Prisma.FieldRef<"TestServer", 'String'>
}
    

// Custom InputTypes
/**
 * TestServer findUnique
 */
export type TestServerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TestServer
   */
  select?: Prisma.TestServerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TestServer
   */
  omit?: Prisma.TestServerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TestServerInclude<ExtArgs> | null
  /**
   * Filter, which TestServer to fetch.
   */
  where: Prisma.TestServerWhereUniqueInput
}

/**
 * TestServer findUniqueOrThrow
 */
export type TestServerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TestServer
   */
  select?: Prisma.TestServerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TestServer
   */
  omit?: Prisma.TestServerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TestServerInclude<ExtArgs> | null
  /**
   * Filter, which TestServer to fetch.
   */
  where: Prisma.TestServerWhereUniqueInput
}

/**
 * TestServer findFirst
 */
export type TestServerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TestServer
   */
  select?: Prisma.TestServerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TestServer
   */
  omit?: Prisma.TestServerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TestServerInclude<ExtArgs> | null
  /**
   * Filter, which TestServer to fetch.
   */
  where?: Prisma.TestServerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TestServers to fetch.
   */
  orderBy?: Prisma.TestServerOrderByWithRelationInput | Prisma.TestServerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TestServers.
   */
  cursor?: Prisma.TestServerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TestServers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TestServers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TestServers.
   */
  distinct?: Prisma.TestServerScalarFieldEnum | Prisma.TestServerScalarFieldEnum[]
}

/**
 * TestServer findFirstOrThrow
 */
export type TestServerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TestServer
   */
  select?: Prisma.TestServerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TestServer
   */
  omit?: Prisma.TestServerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TestServerInclude<ExtArgs> | null
  /**
   * Filter, which TestServer to fetch.
   */
  where?: Prisma.TestServerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TestServers to fetch.
   */
  orderBy?: Prisma.TestServerOrderByWithRelationInput | Prisma.TestServerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TestServers.
   */
  cursor?: Prisma.TestServerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TestServers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TestServers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TestServers.
   */
  distinct?: Prisma.TestServerScalarFieldEnum | Prisma.TestServerScalarFieldEnum[]
}

/**
 * TestServer findMany
 */
export type TestServerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TestServer
   */
  select?: Prisma.TestServerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TestServer
   */
  omit?: Prisma.TestServerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TestServerInclude<ExtArgs> | null
  /**
   * Filter, which TestServers to fetch.
   */
  where?: Prisma.TestServerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TestServers to fetch.
   */
  orderBy?: Prisma.TestServerOrderByWithRelationInput | Prisma.TestServerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TestServers.
   */
  cursor?: Prisma.TestServerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TestServers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TestServers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TestServers.
   */
  distinct?: Prisma.TestServerScalarFieldEnum | Prisma.TestServerScalarFieldEnum[]
}

/**
 * TestServer create
 */
export type TestServerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TestServer
   */
  select?: Prisma.TestServerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TestServer
   */
  omit?: Prisma.TestServerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TestServerInclude<ExtArgs> | null
  /**
   * The data needed to create a TestServer.
   */
  data: Prisma.XOR<Prisma.TestServerCreateInput, Prisma.TestServerUncheckedCreateInput>
}

/**
 * TestServer createMany
 */
export type TestServerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TestServers.
   */
  data: Prisma.TestServerCreateManyInput | Prisma.TestServerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TestServer createManyAndReturn
 */
export type TestServerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TestServer
   */
  select?: Prisma.TestServerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TestServer
   */
  omit?: Prisma.TestServerOmit<ExtArgs> | null
  /**
   * The data used to create many TestServers.
   */
  data: Prisma.TestServerCreateManyInput | Prisma.TestServerCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TestServerIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TestServer update
 */
export type TestServerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TestServer
   */
  select?: Prisma.TestServerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TestServer
   */
  omit?: Prisma.TestServerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TestServerInclude<ExtArgs> | null
  /**
   * The data needed to update a TestServer.
   */
  data: Prisma.XOR<Prisma.TestServerUpdateInput, Prisma.TestServerUncheckedUpdateInput>
  /**
   * Choose, which TestServer to update.
   */
  where: Prisma.TestServerWhereUniqueInput
}

/**
 * TestServer updateMany
 */
export type TestServerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TestServers.
   */
  data: Prisma.XOR<Prisma.TestServerUpdateManyMutationInput, Prisma.TestServerUncheckedUpdateManyInput>
  /**
   * Filter which TestServers to update
   */
  where?: Prisma.TestServerWhereInput
  /**
   * Limit how many TestServers to update.
   */
  limit?: number
}

/**
 * TestServer updateManyAndReturn
 */
export type TestServerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TestServer
   */
  select?: Prisma.TestServerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TestServer
   */
  omit?: Prisma.TestServerOmit<ExtArgs> | null
  /**
   * The data used to update TestServers.
   */
  data: Prisma.XOR<Prisma.TestServerUpdateManyMutationInput, Prisma.TestServerUncheckedUpdateManyInput>
  /**
   * Filter which TestServers to update
   */
  where?: Prisma.TestServerWhereInput
  /**
   * Limit how many TestServers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TestServerIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TestServer upsert
 */
export type TestServerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TestServer
   */
  select?: Prisma.TestServerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TestServer
   */
  omit?: Prisma.TestServerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TestServerInclude<ExtArgs> | null
  /**
   * The filter to search for the TestServer to update in case it exists.
   */
  where: Prisma.TestServerWhereUniqueInput
  /**
   * In case the TestServer found by the `where` argument doesn't exist, create a new TestServer with this data.
   */
  create: Prisma.XOR<Prisma.TestServerCreateInput, Prisma.TestServerUncheckedCreateInput>
  /**
   * In case the TestServer was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TestServerUpdateInput, Prisma.TestServerUncheckedUpdateInput>
}

/**
 * TestServer delete
 */
export type TestServerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TestServer
   */
  select?: Prisma.TestServerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TestServer
   */
  omit?: Prisma.TestServerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TestServerInclude<ExtArgs> | null
  /**
   * Filter which TestServer to delete.
   */
  where: Prisma.TestServerWhereUniqueInput
}

/**
 * TestServer deleteMany
 */
export type TestServerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TestServers to delete
   */
  where?: Prisma.TestServerWhereInput
  /**
   * Limit how many TestServers to delete.
   */
  limit?: number
}

/**
 * TestServer.environment
 */
export type TestServer$environmentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Environment
   */
  select?: Prisma.EnvironmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Environment
   */
  omit?: Prisma.EnvironmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EnvironmentInclude<ExtArgs> | null
  where?: Prisma.EnvironmentWhereInput
}

/**
 * TestServer without action
 */
export type TestServerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TestServer
   */
  select?: Prisma.TestServerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TestServer
   */
  omit?: Prisma.TestServerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TestServerInclude<ExtArgs> | null
}
